"""empty message

Revision ID: 99622cdd90a6
Revises: 65446621209f
Create Date: 2023-04-15 22:28:28.495999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99622cdd90a6'
down_revision = '65446621209f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=30), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('tel_resid', sa.String(length=10), nullable=False),
    sa.Column('tel_cel', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('rg', sa.String(length=8), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venda', sa.Column('vendedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'venda', 'usuario', ['vendedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venda', type_='foreignkey')
    op.drop_column('venda', 'vendedor_id')
    op.drop_table('usuario')
    # ### end Alembic commands ###
