"""empty message

Revision ID: aeda16c32a0d
Revises: 99622cdd90a6
Create Date: 2023-04-16 22:33:55.489160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeda16c32a0d'
down_revision = '99622cdd90a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=30), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('produto', sa.Column('fornecedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'fornecedor', ['fornecedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'fornecedor_id')
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
